### ISSUE TITLE
SSL certificate for ideja.akl.lt

### ISSUE THREAD

**Issue by mgedmin** [akllt/infrastructure#1]
https://ideja.akl.lt/ dabar meta klaidą, nes SSL sertifikatas save identifikuoja kaip 'lists.akl.lt'.  Reiktų naujo sertifikato.

**Comment by mgedmin** [comment]
ideja.akl.lt is dead (hardware failure probably)

**Comment by Baltix** [comment]
ideja.akl.lt yra pas mane dabar, atgaivinsiu kovo men.
