### ISSUE TITLE
ubuntu.lt serverio migracija

### ISSUE THREAD

**Issue by mgedmin** [akllt/infrastructure#11]
Šiuo metu ubuntu.lt sukasi iv-4.pov.lt serveryje, kuris yra OpenVZ konteineris, kurio negalima atnaujinti virš Ubuntu 16.04.  Ubuntu 16.04 LTS perėjo į ESM režimą, t.y. saugumo atnaujinimai mokami.

pov.lt sukūrė naują VPSą -- vaiduoklis.pov.lt -- į kurį reikia perkelti ubuntu.lt ir kitas sveitaines.  Dalis darbo jau padaryta:

- TLS sertifikatai naujame serveryje yra
- ubuntu.lt postfix virtual hostas: https://github.com/ProgrammersOfVilnius/deployments/commit/84d5325af804b8b9f52a1eb5721bff30baebcbed
- https://github.com/akllt/infrastructure/pull/9
- https://vaiduoklis.pov.lt/changelog/2021/05/03/#e9
- https://github.com/akllt/infrastructure/pull/10
- https://vaiduoklis.pov.lt/changelog/2021/05/03/#e10

Kas liko:

- [x] ubuntult.service aprašas systemd -> https://github.com/akllt/infrastructure/pull/12
- [x] sustabdyti svetainę sename serveryje
- [x] nukopijuoti naujausius duomenis iš seno serverio
- [x] nukreipti DNS į naują serverį

Nieko nepamiršau?  @sirex

**Comment by sirex** [comment]
Atrodo, nieko netrūksta.

**Comment by mgedmin** [comment]
Šiaip gera mintis sumažinti Ubuntu.lt DNS TTLą iki 5 minučių (300 sekundžių) dieną prieš pakeičiant IP.

Kiek žinau, aš neturiu priėjimo prie ubuntu.lt DNS.

**Comment by sirex** [comment]
Turiu priėjimą prie ubuntu.lt, galėsiu pakeisti TTL.

**Comment by sirex** [comment]
Patikrinau ir matau, kad viskas veikia. Paeičiau TTL į 15 min (mažiausias galima Interneto Vizijoje) ir ryt pabaigsiu perkėlimą.

**Comment by sirex** [comment]
Perkėlimas baigtas. Ačiū @mgedmin, kad praktiškai viską padarei už mane!

**Comment by mgedmin** [comment]
Tiesa, backupams kokių nors pageidavimų turi?  Šiuo metu ten backupinamas pilnas kasnaktinis PostgreSQL visų duombazių dumpas (bet, per mano neapsižiūrėjimą, jis nėra kopijuojamas offsite).

**Comment by sirex** [comment]
Backupinti reikia PostgreSQL ir `/opt/ubuntu.lt/spirit/media`.
